name: balu_sto
description: A new Flutter project.

version: 1.0.5+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.3

  firebase_core: 1.2.1
  firebase: 9.0.1
  cloud_firestore: 2.2.1
  firebase_auth: 1.3.0
  firebase_storage: 8.1.1
  google_fonts: 2.1.0

  flutter_bloc: 7.0.1
  koin_flutter: 0.11.0-nullsafety.0
  koin: 0.15.0-nullsafety.0
  koin_bloc: 0.2.0-nullsafety.0
  sembast: 3.1.0+2
  package_info: 2.0.2
  path_provider: 2.0.2
  shared_preferences: 2.0.6
  image_picker: 0.8.0+1
  cached_network_image: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/images/
  uses-material-design: true
